### PR TITLE
Add Models to Kitchen

### PR DESCRIPTION
**Pull request by joaorenatopinto**
- [x] Bread
- [x] Tables
- [x] Safe
- [ ] Chairs
- [x] Kitchen stuff

### CODE REVIEW

**Comment by joaorenatopinto** [comment]
Cabinet license :  "Old Kitchen Cabinets" (https://skfb.ly/onGMR) by GameDev Nick is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).

**Comment by joaorenatopinto** [comment]
Shelf : "Old Kitchen Shelf" (https://skfb.ly/onE8X) by GameDev Nick is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).

**Comment by joaorenatopinto** [comment]
https://sketchfab.com/3d-models/restaurant-kitchen-set-part-1-129dd2f84879477ea261b422d21491f4

**Comment by joaorenatopinto** [comment]
Stove: "Gas Stove" (https://skfb.ly/69pGD) by Francesco Coldesina is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).

**Review by JoeMGomes — APPROVED** [review]

**Pull request merged**
